### ISSUE TITLE
tsx watch src/index.ts not reloading the server.

### ISSUE THREAD

**Issue by patelharsh9797** [w3cj/hono-open-api-starter#12]
When i run the npm run dev it's start the server but whenever something update in app.ts it's not reloading the server. 

Any fix for that?

**Comment by w3cj** [comment]
`npm run dev` works for me after fresh repo clone / setup.

What OS are you on? What version of node are you using?

**Comment by patelharsh9797** [comment]
I'm using wsl2 with bun.

Fixed: The issue was the actual file system. Since i was running the dev server from the wsl2 but the actual project was in the Windows file system. I moved the whole project to wsl2/ubuntu file system, and it works.
