### ISSUE TITLE
pnpm test failing

### ISSUE THREAD

**Issue by monsieurBoutte** [w3cj/hono-open-api-starter#13]
Can't thank you enough for this starter template!

That aside, I'm not sure if I'm doing something wrong here but all the test fail when cloning and running this on the latest cloudflare branch. All test return a status 500

<img width="912" alt="Screenshot 2024-11-06 at 10 19 01 PM" src="https://github.com/user-attachments/assets/203a6dcf-d79f-458a-b6bb-e4598e15d1d7">

**Comment by monsieurBoutte** [comment]
Figured it out after hours of debugging 😭  I was going to open a PR to fix it but realized I didn't have permission to open a PR.

In any case, the fix was adding an explicit crypto import in the pino logger

<img width="646" alt="Screenshot 2024-11-07 at 8 23 06 AM" src="https://github.com/user-attachments/assets/59f4fa4a-775e-43aa-b4e3-2923de9d2b96">

**Comment by w3cj** [comment]
Updated the cloudflare template. Thanks!
