### ISSUE TITLE
scalar API's reference page does not show any API on /reference

### ISSUE THREAD

**Issue by xkeshav** [w3cj/hono-open-api-starter#19]
following the instructions from [your hono js video](https://www.youtube.com/watch?v=sNh9PoM9sUE&t=47m]) try to implement scalar, installed the package but when click on `/reference` , it does not show any API refrence but below page

![/reference with scalar](https://github.com/user-attachments/assets/c0e0879a-dc93-4298-a0c7-6f35a6a7c03e)

tane below is `/doc` which shows the json data.

![/doc](https://github.com/user-attachments/assets/e1c6d577-bad1-4e22-8aaf-d8c6941dcae0)

### index.route.ts

```ts
import { createRouter } from "@/libs/create-app";
import { createRoute, z } from "@hono/zod-openapi";

import * as HttpStatusCodes from "@/utils/http-status-codes";

const router = createRouter().openapi(
  createRoute({
    tags: ["Index"],
    method: "get",
    path: "/",
    responses: {
      [HttpStatusCodes.OK]: {
        content: {
          "application/json": {
            schema: z.object({
              message: z.string()
            })
          }
          //"text/html": { schema: z.object({}) }
        },
        description: "TZ API Index"
      }
    }
  }),
  (c) => {
    return c.json({ message: "TZ server" });
  }
);

export default router;

```

### configure-open-api.ts

```ts
import { AppBindings } from "@/middlewares";
import { OpenAPIHono } from "@hono/zod-openapi";
import { apiReference } from "@scalar/hono-api-reference";

type AppOpenAPi = OpenAPIHono<AppBindings>;

import pkg from "../../package.json";

export default function configureOpenAPI(app: AppOpenAPi) {
  app.doc("/doc", {
    openapi: "3.0.0",
    info: {
      version: pkg.version,
      title: "TZ Server"
    }
  });

  app.get(
    "/reference",
    apiReference({
      pageTitle: "API Reference",
      theme: "kepler",
      layout: "modern",
      defaultHttpClient: {
        targetKey: "javascript",
        clientKey: "fetch"
      },
      spec: {
        url: "/doc,"
      }
    })
  );
}

```
### package.json (relevant content )

```json
 {
 "dependencies": {
    "@hono/node-server": "1.13.2",
    "@hono/zod-openapi": "0.16.4",
    "@logtape/logtape": "0.6.3",
    "@scalar/hono-api-reference": "0.5.156",
}
}
```
what could be the issue?

**Comment by w3cj** [comment]
Everything looks okay to me. Not sure what the issue could be. Did you figure this out?

**Comment by goldjunge91** [comment]
![Screenshot-2024-12-11 um 22 18 1tMJNulq000070@2x](https://github.com/user-attachments/assets/8300b906-8788-483d-98dc-433f5763df72)
I get  not the same but Close.
i get it on my own project, as well  on your template @w3cj . i used node 18 and node 20

**Comment by w3cj** [comment]
Looks like this is an issue with the middleware. Please open an issue there: https://github.com/scalar/scalar/blob/main/packages/hono-api-reference/README.md

**Comment by w3cj** [comment]
This is the issue to follow: https://github.com/scalar/scalar/issues/3450

**Comment by w3cj** [comment]
For now you can lock the scalar cdn reference to an older version:

```ts
  app.get(
    "/reference",
    apiReference({
      theme: "kepler",
      layout: "classic",
      cdn: "https://unpkg.com/@scalar/api-reference@1.25.78/dist/browser/standalone.js",
      defaultHttpClient: {
        targetKey: "javascript",
        clientKey: "fetch",
      },
      spec: {
        url: "/doc",
      },
    }),
  );
```

**Comment by goldjunge91** [comment]
i solved the issue with the following approach:
Added the URL configuration to env.ts with a default value:
` URL: z.string().default("localhost:3000"),'`
```
import env from "@/env";

export default function configureOpenAPI(app: AppOpenAPI) {
  app.doc("/doc", {
    openapi: "1.0.0",
    info: {
      version: packageJSON.version,
      title: "Products API",
      description: "API for managing products",
    },
    servers: [
            {
              url:env.URL, 
              description: "Development server",
            },
          ],
        });

  app.get(
    "/reference",
    apiReference({
      spec: {
        url: "/doc",
      },
      theme: "default",
      layout: "modern",
      // cdn: "https://unpkg.com/@scalar/api-reference@1.25.78/dist/browser/standalone.js",
      defaultHttpClient: {
        targetKey: "javascript",
        clientKey: "fetch",
      },
    }),
  );
}
```

Note: I also tested the CDN solution (commented out in the code) which works as an alternative approach.

**Comment by FelipeEmos** [comment]
Oh, I'm sorry I just realized my problem is not the one from the current issue... I have the same problem as @goldjunge91 as he mentioned here: https://github.com/w3cj/hono-open-api-starter/issues/19#issuecomment-2537321877

Should I delete my last comment?
I've just opened an issue about this table problem
- https://github.com/w3cj/hono-open-api-starter/issues/21

**Comment by xkeshav** [comment]
issue with syntax in `spec`; put extra comma inside url  as `url: "/doc,"` cause this issue.

```
 spec: {
        url: "/doc"
      }
 ```

**Comment by xkeshav** [comment]
issue with syntax in `spec`; put extra comma inside url  as `url: "/doc,"` causing this issue. below works

```json
 spec: {
        url: "/doc"
      }
 ```
