### ISSUE TITLE
Using middlewares with typesafe context

### ISSUE THREAD

**Issue by rahulpeacock** [w3cj/hono-open-api-starter#20]
I want to have a auth-middleware for a specific route, from the docs they are recommending to use `middleware` property inside  `createRoute` function. When I do that the type is not being inferred to the handler if I use the approach from the hono-open-api-starter repo

[Docs recommend](https://github.com/oberbeck/honojs-middleware/blob/3ffb66707201f657f9aa37e726ea2ecc2f034acf/packages/zod-openapi/test/index.test-d.ts#L268-L304)

```ts
// chapter.routes.ts
export const createChapter = createRoute({
  method: 'post',
  path: '/course/{course_id}/chapter',
  tags: ['Chapter'],
  middleware: [
    createMiddleware<{
      Variables: { foo: string };
    }>((c, next) => {
      c.set('foo', 'abc');
      return next();
    }),
  ] as const,
  request: {
    params: createChapterRequestSchema.params,
    body: createChapterRequestSchema.body,
  },
  responses: {
    [HttpStatusCodes.UNPROCESSABLE_ENTITY]: jsonContent(
      createErrorSchema(createChapterRequestSchema.params).or(createErrorSchema(createChapterRequestSchema.body)),
      'Validation error',
    ),
    [HttpStatusCodes.CREATED]: jsonContent(
      z.object({
        success: z.boolean(),
        message: z.string(),
        chapter_id: z.number(),
      }),
      'Chapter created successfully',
    ),
  },
});

export type CreateChapterRoute = typeof createChapter;
```

I am not getting the typesafe inside the handler and also an error like this

![image](https://github.com/user-attachments/assets/17c9985e-acae-4507-b787-b1ecae2b8a80)

I have implemented the same from the docs. 

Is there a way to have typesafe middlewares inside the hono-open-api-starter for auth-routes

**Comment by w3cj** [comment]
You can create another helper type for this:

In `lib/types.ts` - update `AppRouteHandler` to allow passing in an updated `Env` type - add the `AppMiddlewareVariables` type

```ts
import type { OpenAPIHono, RouteConfig, RouteHandler } from "@hono/zod-openapi";
import type { Env } from "hono";
import type { PinoLogger } from "hono-pino";

export interface AppBindings {
  Variables: {
    logger: PinoLogger;
  };
};

export type AppOpenAPI = OpenAPIHono<AppBindings>;

// Update this
export type AppRouteHandler<R extends RouteConfig, A extends Env = AppBindings> = RouteHandler<R, A>;

// Add this
export type AppMiddlewareVariables<T extends object> = AppBindings & {
  Variables: T;
};
```

You can then use it like this in `tasks.handlers.ts`

```ts
export const list: AppRouteHandler<ListRoute, AppMiddlewareVariables<{
  foo: string;
}>> = async (c) => {
  const tasks = await db.query.tasks.findMany();
  return c.json(tasks);
};
```

**Comment by rahulpeacock** [comment]
But how to use middleware with `zod-openapi`. It's quite different than using `app.use()` in normal hono

**Comment by w3cj** [comment]
The code I provided will fix the type error from your original comment.

**Comment by rahulpeacock** [comment]
@w3cj Thanks the code is very helpful and also works perfect.

In case anyone want to know more on how to use middlewares with hono-zod-openapi 
- https://github.com/honojs/middleware/issues/637#issuecomment-2461822515
- https://github.com/oberbeck/honojs-middleware/blob/3ffb66707201f657f9aa37e726ea2ecc2f034acf/packages/zod-openapi/test/index.test-d.ts#L268-L304

**Comment by frankhale** [comment]
I'd like to set an environment variable in a route and then get that variable in a middleware. This scenario does not seem to work and the variable will be undefined in the middleware. For instance, my login route will set a variable and then on subsequent requests a middleware needs to look at that variable but it's always undefined. This seems like a pretty common scenario. Is there a way to do this?
