### ISSUE TITLE
Updates to package.json causes issues

### ISSUE THREAD

**Issue by ArmantG** [w3cj/hono-open-api-starter#25]
Seems that when using the latest versions of drizzle packages, there are issues in the schema and drizzle config. 

would be nice if someone more familiar with Hono, drizzle and turso could have a look and comment some fixes? 

![CleanShot 2024-12-31 at 21 22 34@2x](https://github.com/user-attachments/assets/9096cce8-cd12-4d31-8567-f6077b32d33c)
![CleanShot 2024-12-31 at 21 23 27@2x](https://github.com/user-attachments/assets/e66b39f1-c510-43e7-87e8-190567468d92)

**Comment by w3cj** [comment]
Checkout the [drizzle-v0.35](https://github.com/w3cj/hono-open-api-starter/tree/drizzle-v0.35) branch for a working example.
