### ISSUE TITLE
Redundant createTestApp

### ISSUE THREAD

**Issue by bostjanpisler** [w3cj/hono-open-api-starter#8]
https://github.com/w3cj/hono-open-api-starter/blob/fd4c7176d82646b295f54b52868f1894ccfde413/src/lib/create-app.ts#L26

The createTestApp function is not used in the test example, not sure if it's redundant or not for the starter.

**Comment by w3cj** [comment]
It is redundant after a re-factor. I show it in the original video though, so I'll keep it around.
