### ISSUE TITLE
How to define route level middleware

### ISSUE THREAD

**Issue by bostjanpisler** [w3cj/hono-open-api-starter#9]
How can route level middleware be defined ie. only for tasks endpoints, not the whole app?

**Comment by enyelsequeira** [comment]
this should not be an issue rather than maybe a discussion, 
createRoute that comes from `@hono/zod-openapi` allows you to send an array of the middlewares you want to run example below 

```ts
const updateUser = createRoute({
  ...UserRoutesGeneral,
  method: "patch", // Using PATCH for partial updates
  path: "/users/{userId}", // RESTful path pattern
  middleware: [isUserAuthenticated], // Must be logged in
````

**Comment by w3cj** [comment]
See the section in the @hono/zod-openapi docs "Configure middleware for each endpoint" - https://github.com/honojs/middleware/tree/main/packages/zod-openapi#configure-middleware-for-each-endpoint

Closing this. Please open a discussion thread if you need more help.
